Repository kidstylex/TELLING, pull requests merged in 2020-11, with the labels that each got.

#37 Feature create story scroll mode
  TELLING/forms.py
  TELLING/models.py
  TELLING/templates/base.html
  TELLING/templates/create_story.html
  TELLING/urls.py
  TELLING/views.py
  mysite/settings.py
  mysite/urls.py
Labels: enhancement

#38 Feature display story scroll mode
  TELLING/static/Homepage/CSS/style.css
  TELLING/templates/index.html
  TELLING/templates/story_detail.html
  TELLING/urls.py
  TELLING/views.py
Labels: enhancement, task

#39 Improve ui login and register form
  TELLING/static/Base/css/style.base.css
  TELLING/static/Homepage/CSS/style.css
  TELLING/static/Login/css/style.login.css
  TELLING/static/Register/css/style.regis.css
  TELLING/templates/base.html
  TELLING/templates/login.html
  TELLING/templates/registration.html
  image/upload/GettyImages-85216701.jpg
  image/upload/IMG_8090.JPG
  image/upload/c84c747c7266eb5b14019ef4b5111027.1000x1000x1.jpg
  login/urls.py
  login/views.py
  media/profile_pics/Ea9-uFEUYAM0s1R.jpeg
  media/upload/IMG_1102.JPG
Labels: design

#40 Seperate secret from settings.py to .env
  .gitignore
  TELLING/views.py
  login/views.py
  media/upload/81iqZ2HHD-L.jpg
  media/upload/Odyssey-crop.jpg
  media/upload/Sonnets1609titlepage.jpg
  mysite/settings.py
Labels: enhancement
